// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-west-2:884e9809-eb4c-4409-a0b3-e76ef0ad1cf1',
    'aws_cognito_region': 'us-west-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'amplifyangulartest-hosting-mobilehub-165456612',
    'aws_content_delivery_bucket_region': 'us-west-1',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'dczl52wgnl3yi.cloudfront.net',
    'aws_mobile_analytics_app_id': '56ea9d827b4749209dcd8dc5b905348f',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'a1b7919d-d170-4389-bab8-5024652f6fb9',
    'aws_project_name': 'amplify-angular-test-2018-04-16-15-15-08',
    'aws_project_region': 'us-west-1',
    'aws_resource_name_prefix': 'amplifyangulartest-mobilehub-165456612',
}

export default awsmobile;
